### ISSUE TITLE
429 too many requests

### ISSUE THREAD

**Issue by nordicgit70** [timkpaine/iexjs#144]
The 429 error with too many requests should be caught by IEX.js in its fetch `while-loop`. The calling application still receives 429 errors when retrieving data for 25 stocks.

The expected behavior would be to not receive 429 errors.

The problem is caused by the fact that the sleep time is too short. `Math.random() * 50 * tries` triggers a sleep delay of just a few milliseconds.

Resolution to have a minimal delay and to increase the sleep delay e.g. `Math.max(50, Math.random() * 250 * tries)`.

**Comment by timkpaine** [comment]
This is a fine change, I would merge a PR with this change
