### ISSUE TITLE
"list" argument must be an Array of Buffers

### ISSUE THREAD

**Issue by DushanMinic** [timkpaine/iexjs#39]
**Describe the bug**
I'm trying to connect to price streaming over SSE, but the process crashes with the error from the screenshot. I've noticed that if I pass 18 symbols, the app doesn't crash, but if I pass 19, it crashes. Don't know if it's connected to the number of symbols passing as an argument.

**To Reproduce**
```javascript
const { Client } = require('iexjs');

const client = new Client({ api_token: '123', version: 'sandbox' });

client.topsSSE('apd,rrc,wec,nyt,rdc,ms,abt,nem,adm,irm,iff,v,ma,ldos,pnw,ma,v,msft,amzn', ([data]) => {
    console.log(data.symbol);
});
```

**Expected behavior**
Not expecting the error, but rather an influx of prices.

**Screenshots**
![Screen Shot 2021-04-28 at 2 53 47 PM](https://user-images.githubusercontent.com/12270056/116407112-b5175080-a831-11eb-8b2a-cf43a9626a22.png)

**Comment by DushanMinic** [comment]
Any progress on this?

**Comment by DushanMinic** [comment]
Hey @timkpaine  - I've tried the simple example with only using EventSource directly, and not the IEX library itself. And it works fine. Wanted to see if there's maybe a bug in the ES lib itself for Node.js.

```javascript
const EventSource = require('eventsource');

const symbolIds = 'apd,rrc,wec,nyt,rdc,ms,abt,nem,adm,irm,iff,v,ma,ldos,pnw,ma,v,msft,amzn,fb,gild,hlit';
const token = '123'

const url = `https://sandbox-sse.iexapis.com/stable/tops?symbols=${symbolIds}&token=${token}`;

const es = new EventSource(url);

es.onmessage = function (message) {
    console.log((JSON.parse(message?.data))[0]);
}

es.onerror = function (error) {
    console.error({ error });
    process.exit(1);
}

```

I also used one of your tests to connect to SSE streaming, to test whether the problem persists there with unbundled code.

```javascript
const fetch = require("cross-fetch");
const { Client } = require("../src/js");

const SYMBOL = "BAC";

beforeAll(() => {
  global.fetch = fetch;
});

// set timeout to 30s for long calls
jest.setTimeout(50000);

afterEach(async () => {
  await new Promise((r) => setTimeout(r, 500));
});

function getTick() {
  return new Promise((resolve, reject) => {
    const token = "123";

    const client = new Client({ api_token: token, version: "sandbox" });
    let ticks = 0;

    client.topsSSE(
      "apd,rrc,wec,nyt,rdc,ms,abt,nem,adm,irm,iff,v,ma,ldos,pnw,ma,v,msft,amzn",
      (response) => {
        ticks += 1;
        console.log({ response, ticks });
        if (ticks === 10000) {
          resolve(response);
        }
      },
    );
  });
}

describe("Client", () => {
  test.only("Exists", async () => {
    expect(Client).toBeDefined();

    await getTick();
  });
});
```

And I get no errors there either. But when I use your library, which uses the code from **dist** folder, I keep getting errors that I mentioned in the first post. It's being triggered in this part of the bundled code with rollup: **if (!internalIsBuffer(buf)) {**:

```javascript
Buffer$1.concat = function concat(list, length) {
  if (!isArray(list)) {
    throw new TypeError('"list" argument must be an Array of Buffers')
  }

  if (list.length === 0) {
    return Buffer$1.alloc(0)
  }

  var i;
  if (length === undefined) {
    length = 0;
    for (i = 0; i < list.length; ++i) {
      length += list[i].length;
    }
  }

  var buffer = Buffer$1.allocUnsafe(length);
  var pos = 0;
  for (i = 0; i < list.length; ++i) {
    var buf = list[i];
    if (!internalIsBuffer(buf)) {
      throw new TypeError('"list" argument must be an Array of Buffers')
    }
    buf.copy(buffer, pos);
    pos += buf.length;
  }
  return buffer
};
```


Also, I noticed that you've got a typo in **topsSSE** function.

```javascript
export const topsSSE = (symbols, on_data, { token, version } = {}) =>
  _runSSE("tops", symbols, on_data, token, version);
```
**_runSSE** method is not passed arguments properly, it's missing curly brackets for token and version like this. They're undefined instead.

```javascript
 _runSSE("tops", symbols, on_data, { token, version});
```

I have a hard time finding out, why it works with unbundled code, but it doesn't with the one from rollup. Any help is greatly appreciated, I'd gladly like to use the IEX library itself, than EventSource directly.

Thanks!

**Comment by timkpaine** [comment]
@DushanMinic i will open a separate issue for the argument thing, i've been migrating stuff from discrete arguments to options objects.

For rollup, fetch and event source are polyfilled when running via Node since they only exist in the browser ([here](https://github.com/iexcloud/iexjs/blob/main/rollup.config.js#L64) in rollup which says to use https://github.com/Yaffle/EventSource). But it looks like its coming from the polyfilled [buffer-es6](https://github.com/calvinmetcalf/buffer-es6/blob/master/index.js#L401). And indeed i seem some relevant tickets filed there: https://github.com/calvinmetcalf/buffer-es6/issues/6
