### ISSUE TITLE
time-series should not use 'limit=1' when specifying a range

### ISSUE THREAD

**Issue by illoRocks** [timkpaine/iexjs#68]
Hi,
If you specify the 'range' as an option in timeseries the limit is automatically set to 1. I don't think that this is the desired behavior. When specifying the range, I would assume that the full range will be downloaded.

For example:
```js
client.timeSeries({
      id: 'BALANCE_SHEET',
      key: 'AAPL',
      range: '4y'
})
```
The code above will use the following url:
https://sandbox.iexapis.com/stable/time-series/BALANCE_SHEET/AAPL?range=4y&limit=1&token=...

**Comment by timkpaine** [comment]
You don't necessarily know how many records are in the range and the default is always to opt for the option that charges the least credits. I'm open to alternatives but the motivation is for protective defaults.
